import { defineStore } from 'pinia';

export type AppLanguage = 'en' | 'es';

export type UserAddress = {
  country: string;
  city: string;
  address: string;
};

const LANGUAGE_KEY = 'autovalor_language';
const ADDRESS_KEY_PREFIX = 'autovalor_address_';

function userAddressKey(userId?: number | string | null) {
  return `${ADDRESS_KEY_PREFIX}${userId || 'guest'}`;
}

function readLanguage(): AppLanguage {
  const value = window.localStorage.getItem(LANGUAGE_KEY);
  return value === 'es' ? 'es' : 'en';
}

function readAddress(userId?: number | string | null): UserAddress {
  try {
    const raw = window.localStorage.getItem(userAddressKey(userId));
    if (!raw) return { country: '', city: '', address: '' };
    return { country: '', city: '', address: '', ...JSON.parse(raw) };
  } catch {
    return { country: '', city: '', address: '' };
  }
}

function writeAddress(userId: number | string | null | undefined, address: UserAddress) {
  window.localStorage.setItem(userAddressKey(userId), JSON.stringify(address));
}

const translations = {
  en: {
    // Common
    retry: 'Retry',
    close: 'Close',
    clear: 'Clear',
    clearAll: 'Clear All',
    reset: 'Reset',
    save: 'Save',
    saved: 'Saved',
    update: 'Update',
    delete: 'Delete',
    deleting: 'Deleting...',
    saving: 'Saving...',
    loading: 'Loading...',
    available: 'Available',
    vehicle: 'Vehicle',
    seller: 'Seller',
    owner: 'Owner',
    price: 'Price',
    description: 'Description',
    contact: 'Contact',
    manage: 'Manage',
    yes: 'Yes',
    no: 'No',

    // Tabs / profile
    profileTitle: 'My Profile',
    editProfile: 'Edit Profile',
    listings: 'Listings',
    address: 'Address',
    notification: 'Notification',
    payment: 'Payment',
    security: 'Security',
    language: 'Language',
    darkMode: 'Dark Mode',
    privacyPolicy: 'Privacy Policy',
    helpCenter: 'Help Center',
    inviteFriends: 'Invite Friends',
    logout: 'Logout',
    loggingOut: 'Logging out...',
    maintenanceTitle: 'Service under maintenance',
    maintenanceMessage: '{section} is under maintenance. This feature will be available soon.',
    understood: 'Got it',
    home: 'Home',
    orders: 'Orders',
    sell: 'Sell',
    message: 'Messages',
    profile: 'Profile',
    autoValorUser: 'AutoValor User',
    noEmailAvailable: 'No email available',
    couldNotLoadProfile: 'Could not load your profile.',

    // Language / address
    languageTitle: 'Language',
    languageSubtitle: 'Choose the language used in AutoValor.',
    english: 'English (US)',
    spanish: 'Spanish',
    autoValorInEnglish: 'AutoValor in English',
    autoValorInSpanish: 'AutoValor in Spanish',
    addressTitle: 'Address',
    addressSubtitle: 'Save your city and country so buyers can see the approximate seller location.',
    country: 'Country',
    city: 'City',
    streetAddress: 'Address',
    countryPlaceholder: 'Spain',
    cityPlaceholder: 'Barcelona',
    addressPlaceholder: 'Street, number, postal code...',
    saveAddress: 'Save address',
    addressSaved: 'Address saved successfully.',

    // Home
    searchCar: 'Search car',
    loadingListings: 'Loading listings...',
    latestListings: 'Latest listings',
    searchBrand: 'Search brand',
    more: 'More',
    featuredListings: 'Featured listings',
    seeAll: 'See all',
    noListingsYet: 'No listings yet',
    createFirstListing: 'Create the first listing from the sell tab.',
    createListing: 'Create listing',
    couldNotLoadListings: 'Could not load listings.',

    // Search
    search: 'Search',
    openFilters: 'Open filters',
    recent: 'Recent',
    resultsFor: 'Results for',
    allCars: 'All cars',
    found: 'found',
    loadingResults: 'Loading results...',
    noCarsFound: 'No cars found',
    tryAnotherSearch: 'Try another search or change filters.',
    couldNotLoadSearchResults: 'Could not load search results.',
    filterCars: 'Filter cars',
    brand: 'Brand',
    anyBrand: 'Any brand',
    minPrice: 'Min price',
    maxPrice: 'Max price',
    minYear: 'Min year',
    maxYear: 'Max year',
    minKm: 'Min km',
    maxKm: 'Max km',
    fuel: 'Fuel',
    anyFuel: 'Any fuel',
    transmission: 'Transmission',
    any: 'Any',
    body: 'Body',
    anyBody: 'Any body',
    sortBy: 'Sort by',
    newest: 'Newest',
    priceLowHigh: 'Price: low to high',
    priceHighLow: 'Price: high to low',
    yearNewest: 'Year: newest',
    yearOldest: 'Year: oldest',
    kmLowHigh: 'Km: low to high',
    kmHighLow: 'Km: high to low',
    applyFilters: 'Apply filters',
    cheapestFirst: 'Cheapest first',
    mostExpensive: 'Most expensive',
    newestYear: 'Newest year',
    oldestYear: 'Oldest year',
    lowestKm: 'Lowest km',
    highestKm: 'Highest km',
    from: 'From',
    until: 'Until',

    // Auth
    loginTitle: 'Login to your Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    rememberMe: 'Remember me',
    signIn: 'Sign in',
    signUp: 'Sign up',
    forgotPassword: 'Forgot the password?',
    orContinueWith: 'or continue with',
    dontHaveAccount: 'Don’t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    createAccountTitle: 'Create your Account',
    fullName: 'Full name',
    profileLaterHint: 'You can complete your profile later from the profile screen.',
    enterEmailPassword: 'Enter your email and password.',
    couldNotSignIn: 'Could not sign in.',
    socialLoginNotConnected: 'Social login is not connected yet.',
    completeRegisterFields: 'Complete your name, email and password.',
    passwordMinLength: 'Password must be at least 8 characters.',
    passwordsDoNotMatch: 'Passwords do not match.',
    couldNotCreateAccount: 'Could not create the account.',
    showPassword: 'Show password',
    togglePasswordVisibility: 'Toggle password visibility',

    // Edit profile
    role: 'Role',
    memberSince: 'Member since',
    profileStorageHint: 'For now AutoValor stores your name and email. More profile fields will be connected later.',
    fullNameRequired: 'Full name is required.',
    emailRequired: 'Email is required.',
    profileUpdated: 'Profile updated.',
    couldNotUpdateProfile: 'Could not update your profile.',

    // Sell
    sellYourCar: 'Sell your car',
    reviewListing: 'Review listing',
    sellSubtitlePhotos: 'Follow the photo guide so AutoValor can fill the listing.',
    sellSubtitleReview: 'Check the details before publishing.',
    aiVehicleScan: 'AI vehicle scan',
    aiVehicleScanText: 'Upload the photos in the suggested order. AutoValor will use them to detect the vehicle and prepare the listing template.',
    photoGuide: 'Photo guide',
    selected: 'selected',
    front: 'Front',
    frontDescription: 'Main exterior photo',
    rear: 'Rear',
    rearDescription: 'Back of the vehicle',
    side: 'Side',
    sideDescription: 'Full side profile',
    interior: 'Interior',
    interiorDescription: 'Seats and cabin',
    dashboard: 'Dashboard',
    dashboardDescription: 'Mileage if visible',
    engineExtra: 'Engine / Extra',
    engineExtraDescription: 'Engine or documents',
    tipsForBetterAi: 'Tips for better AI results',
    tipClearPhotos: 'Use clear photos with good light.',
    tipDashboard: 'Include the dashboard if mileage is visible.',
    tipExtra: 'Add an engine or document photo only if it helps identify the vehicle.',
    analyzeVehicle: 'Analyze vehicle',
    vehicleListing: 'Vehicle listing',
    aiNotes: 'AI notes',
    basicInformation: 'Basic information',
    title: 'Title',
    model: 'Model',
    year: 'Year',
    mileage: 'Mileage',
    details: 'Details',
    locationCity: 'City',
    province: 'Province',
    bodyType: 'Body type',
    color: 'Color',
    doors: 'Doors',
    powerCv: 'Power CV',
    engine: 'Engine',
    ecoLabel: 'Eco label',
    warranty: 'Warranty',
    financeable: 'Financeable',
    serviceBook: 'Service book',
    editPhotos: 'Edit photos',
    publishListing: 'Publish listing',
    uploadAtLeastOnePhoto: 'Upload at least one vehicle photo.',
    couldNotAnalyzeVehicle: 'Could not analyze the vehicle.',
    titleRequired: 'Title is required.',
    brandRequired: 'Brand is required.',
    modelRequired: 'Model is required.',
    yearInvalid: 'Year is not valid.',
    mileageInvalid: 'Mileage is not valid.',
    priceInvalid: 'Price is not valid.',
    listingPublished: 'Listing published successfully.',
    couldNotPublishListing: 'Could not publish the listing.',
    privateSeller: 'Private seller',

    // Detail
    loadingCar: 'Loading car...',
    carNotFound: 'Car not found',
    listedOn: 'Listed on',
    manageYourListing: 'Manage your listing',
    manageListingSubtitle: 'Update status, price or description.',
    saveChanges: 'Save changes',
    deleteListing: 'Delete listing permanently?',
    listingUpdated: 'Listing updated successfully.',
    couldNotUpdateListing: 'Could not update listing.',
    couldNotDeleteListing: 'Could not delete listing.',
    noDescriptionProvided: 'No description provided.',
    galleryPhotos: 'Gallery Photos',
    vehicleDetails: 'Vehicle details',
    power: 'Power',
    sellerLocation: 'Seller Location',
    sellerLocationUnavailable: 'Seller location not available yet',
    makeOffer: 'Make offer',
    couldNotStartConversation: 'Could not start the conversation.',

    // Wishlist
    myWishlist: 'My Wishlist',
    loadingWishlist: 'Loading wishlist...',
    wishlistEmpty: 'Your wishlist is empty',
    addCarsFromHome: 'Add cars from Home to see them here.',
    couldNotLoadWishlist: 'Could not load wishlist.',

    // Messages / chat
    chats: 'Chats',
    loadingConversations: 'Loading conversations...',
    noConversationsYet: 'No conversations yet.',
    contactSellerFromDetail: 'Contact a seller from a vehicle detail page.',
    conversationStarted: 'Conversation started',
    yesterday: 'Yesterday',
    couldNotLoadConversations: 'Could not load conversations.',
    conversation: 'Conversation',
    loadingMessages: 'Loading messages...',
    noMessagesYet: 'No messages yet.',
    sendFirstMessage: 'Send the first message about this vehicle.',
    vehicleOffer: 'Vehicle offer',
    buyer: 'Buyer',
    buyerOffers: '{buyer} offers',
    accept: 'Accept',
    reject: 'Reject',
    offerAccepted: 'Offer accepted',
    offerRejected: 'Offer rejected',
    sellerAcceptedOffer: 'The seller accepted your offer.',
    sellerRejectedOffer: 'The seller rejected your offer.',
    orderDelivered: 'Order delivered',
    orderDeliveredText: 'The order has arrived at its destination.',
    completed: 'COMPLETED',
    view: 'View',
    messagePlaceholder: 'Message...',
    couldNotLoadChat: 'Could not load the chat.',
    couldNotSendMessage: 'Could not send the message.',
    couldNotAnswerOffer: 'Could not answer the offer.',

    // Orders
    myOrders: 'My Orders',
    active: 'Active',
    noActiveOrders: 'No active orders',
    acceptedOffersAppear: 'Accepted offers will appear here after checkout.',
    trackOrder: 'Track Order',
    noCompletedOrders: 'No completed orders',
    deliveredOrdersAppear: 'Delivered orders will appear here.',
    leaveReview: 'Leave Review',
    reviewSimulated: 'Review for {id} (simulated)',
  },
  es: {
    // Common
    retry: 'Reintentar',
    close: 'Cerrar',
    clear: 'Limpiar',
    clearAll: 'Borrar todo',
    reset: 'Restablecer',
    save: 'Guardar',
    saved: 'Guardado',
    update: 'Actualizar',
    delete: 'Eliminar',
    deleting: 'Eliminando...',
    saving: 'Guardando...',
    loading: 'Cargando...',
    available: 'Disponible',
    vehicle: 'Vehículo',
    seller: 'Vendedor',
    owner: 'Propietario',
    price: 'Precio',
    description: 'Descripción',
    contact: 'Contactar',
    manage: 'Gestionar',
    yes: 'Sí',
    no: 'No',

    // Tabs / profile
    profileTitle: 'Mi perfil',
    editProfile: 'Editar perfil',
    listings: 'Anuncios',
    address: 'Dirección',
    notification: 'Notificaciones',
    payment: 'Pago',
    security: 'Seguridad',
    language: 'Idioma',
    darkMode: 'Modo oscuro',
    privacyPolicy: 'Política de privacidad',
    helpCenter: 'Centro de ayuda',
    inviteFriends: 'Invitar amigos',
    logout: 'Cerrar sesión',
    loggingOut: 'Cerrando sesión...',
    maintenanceTitle: 'Servicio en mantenimiento',
    maintenanceMessage: '{section} está en mantenimiento. Esta funcionalidad estará disponible próximamente.',
    understood: 'Entendido',
    home: 'Inicio',
    orders: 'Pedidos',
    sell: 'Vender',
    message: 'Mensajes',
    profile: 'Perfil',
    autoValorUser: 'Usuario de AutoValor',
    noEmailAvailable: 'Email no disponible',
    couldNotLoadProfile: 'No se pudo cargar tu perfil.',

    // Language / address
    languageTitle: 'Idioma',
    languageSubtitle: 'Elige el idioma que se usará en AutoValor.',
    english: 'Inglés (US)',
    spanish: 'Español',
    autoValorInEnglish: 'AutoValor en inglés',
    autoValorInSpanish: 'AutoValor en español',
    addressTitle: 'Dirección',
    addressSubtitle: 'Guarda tu ciudad y país para que los compradores vean la ubicación aproximada del vendedor.',
    country: 'País',
    city: 'Ciudad',
    streetAddress: 'Dirección',
    countryPlaceholder: 'España',
    cityPlaceholder: 'Barcelona',
    addressPlaceholder: 'Calle, número, código postal...',
    saveAddress: 'Guardar dirección',
    addressSaved: 'Dirección guardada correctamente.',

    // Home
    searchCar: 'Buscar coche',
    loadingListings: 'Cargando anuncios...',
    latestListings: 'Últimos anuncios',
    searchBrand: 'Buscar marca',
    more: 'Más',
    featuredListings: 'Anuncios destacados',
    seeAll: 'Ver todos',
    noListingsYet: 'No hay anuncios todavía',
    createFirstListing: 'Crea el primer anuncio desde la pestaña vender.',
    createListing: 'Crear anuncio',
    couldNotLoadListings: 'No se pudieron cargar los anuncios.',

    // Search
    search: 'Buscar',
    openFilters: 'Abrir filtros',
    recent: 'Recientes',
    resultsFor: 'Resultados para',
    allCars: 'Todos los coches',
    found: 'encontrados',
    loadingResults: 'Cargando resultados...',
    noCarsFound: 'No se han encontrado coches',
    tryAnotherSearch: 'Prueba otra búsqueda o cambia los filtros.',
    couldNotLoadSearchResults: 'No se pudieron cargar los resultados.',
    filterCars: 'Filtrar coches',
    brand: 'Marca',
    anyBrand: 'Cualquier marca',
    minPrice: 'Precio mínimo',
    maxPrice: 'Precio máximo',
    minYear: 'Año mínimo',
    maxYear: 'Año máximo',
    minKm: 'Km mínimos',
    maxKm: 'Km máximos',
    fuel: 'Combustible',
    anyFuel: 'Cualquier combustible',
    transmission: 'Transmisión',
    any: 'Cualquiera',
    body: 'Carrocería',
    anyBody: 'Cualquier carrocería',
    sortBy: 'Ordenar por',
    newest: 'Más recientes',
    priceLowHigh: 'Precio: de menor a mayor',
    priceHighLow: 'Precio: de mayor a menor',
    yearNewest: 'Año: más nuevo',
    yearOldest: 'Año: más antiguo',
    kmLowHigh: 'Km: de menor a mayor',
    kmHighLow: 'Km: de mayor a menor',
    applyFilters: 'Aplicar filtros',
    cheapestFirst: 'Más baratos primero',
    mostExpensive: 'Más caros primero',
    newestYear: 'Año más nuevo',
    oldestYear: 'Año más antiguo',
    lowestKm: 'Menos km',
    highestKm: 'Más km',
    from: 'Desde',
    until: 'Hasta',

    // Auth
    loginTitle: 'Inicia sesión en tu cuenta',
    email: 'Email',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    rememberMe: 'Recordarme',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    forgotPassword: '¿Has olvidado la contraseña?',
    orContinueWith: 'o continúa con',
    dontHaveAccount: '¿No tienes cuenta?',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    createAccountTitle: 'Crea tu cuenta',
    fullName: 'Nombre completo',
    profileLaterHint: 'Puedes completar tu perfil más tarde desde la pantalla de perfil.',
    enterEmailPassword: 'Introduce tu email y contraseña.',
    couldNotSignIn: 'No se pudo iniciar sesión.',
    socialLoginNotConnected: 'El login social todavía no está conectado.',
    completeRegisterFields: 'Completa tu nombre, email y contraseña.',
    passwordMinLength: 'La contraseña debe tener al menos 8 caracteres.',
    passwordsDoNotMatch: 'Las contraseñas no coinciden.',
    couldNotCreateAccount: 'No se pudo crear la cuenta.',
    showPassword: 'Mostrar contraseña',
    togglePasswordVisibility: 'Mostrar u ocultar contraseña',

    // Edit profile
    role: 'Rol',
    memberSince: 'Miembro desde',
    profileStorageHint: 'Por ahora AutoValor guarda tu nombre y email. Más campos del perfil se conectarán más adelante.',
    fullNameRequired: 'El nombre completo es obligatorio.',
    emailRequired: 'El email es obligatorio.',
    profileUpdated: 'Perfil actualizado.',
    couldNotUpdateProfile: 'No se pudo actualizar tu perfil.',

    // Sell
    sellYourCar: 'Vende tu coche',
    reviewListing: 'Revisar anuncio',
    sellSubtitlePhotos: 'Sigue la guía de fotos para que AutoValor pueda completar el anuncio.',
    sellSubtitleReview: 'Revisa los datos antes de publicar.',
    aiVehicleScan: 'Análisis del vehículo con IA',
    aiVehicleScanText: 'Sube las fotos en el orden recomendado. AutoValor las usará para detectar el vehículo y preparar la plantilla del anuncio.',
    photoGuide: 'Guía de fotos',
    selected: 'seleccionadas',
    front: 'Frontal',
    frontDescription: 'Foto exterior principal',
    rear: 'Trasera',
    rearDescription: 'Parte trasera del vehículo',
    side: 'Lateral',
    sideDescription: 'Perfil lateral completo',
    interior: 'Interior',
    interiorDescription: 'Asientos y habitáculo',
    dashboard: 'Salpicadero',
    dashboardDescription: 'Kilometraje si es visible',
    engineExtra: 'Motor / Extra',
    engineExtraDescription: 'Motor o documentos',
    tipsForBetterAi: 'Consejos para mejorar la IA',
    tipClearPhotos: 'Usa fotos claras y con buena luz.',
    tipDashboard: 'Incluye el salpicadero si el kilometraje es visible.',
    tipExtra: 'Añade una foto del motor o documentos solo si ayuda a identificar el vehículo.',
    analyzeVehicle: 'Analizar vehículo',
    vehicleListing: 'Anuncio del vehículo',
    aiNotes: 'Notas de la IA',
    basicInformation: 'Información básica',
    title: 'Título',
    model: 'Modelo',
    year: 'Año',
    mileage: 'Kilometraje',
    details: 'Detalles',
    locationCity: 'Ciudad',
    province: 'Provincia',
    bodyType: 'Tipo de carrocería',
    color: 'Color',
    doors: 'Puertas',
    powerCv: 'Potencia CV',
    engine: 'Motor',
    ecoLabel: 'Etiqueta ambiental',
    warranty: 'Garantía',
    financeable: 'Financiable',
    serviceBook: 'Libro de mantenimiento',
    editPhotos: 'Editar fotos',
    publishListing: 'Publicar anuncio',
    uploadAtLeastOnePhoto: 'Sube al menos una foto del vehículo.',
    couldNotAnalyzeVehicle: 'No se pudo analizar el vehículo.',
    titleRequired: 'El título es obligatorio.',
    brandRequired: 'La marca es obligatoria.',
    modelRequired: 'El modelo es obligatorio.',
    yearInvalid: 'El año no es válido.',
    mileageInvalid: 'El kilometraje no es válido.',
    priceInvalid: 'El precio no es válido.',
    listingPublished: 'Anuncio publicado correctamente.',
    couldNotPublishListing: 'No se pudo publicar el anuncio.',
    privateSeller: 'Vendedor particular',

    // Detail
    loadingCar: 'Cargando coche...',
    carNotFound: 'Coche no encontrado',
    listedOn: 'Publicado el',
    manageYourListing: 'Gestiona tu anuncio',
    manageListingSubtitle: 'Actualiza el estado, el precio o la descripción.',
    saveChanges: 'Guardar cambios',
    deleteListing: '¿Eliminar este anuncio permanentemente?',
    listingUpdated: 'Anuncio actualizado correctamente.',
    couldNotUpdateListing: 'No se pudo actualizar el anuncio.',
    couldNotDeleteListing: 'No se pudo eliminar el anuncio.',
    noDescriptionProvided: 'No hay descripción disponible.',
    galleryPhotos: 'Fotos de la galería',
    vehicleDetails: 'Detalles del vehículo',
    power: 'Potencia',
    sellerLocation: 'Ubicación del vendedor',
    sellerLocationUnavailable: 'La ubicación del vendedor todavía no está disponible',
    makeOffer: 'Hacer oferta',
    couldNotStartConversation: 'No se pudo iniciar la conversación.',

    // Wishlist
    myWishlist: 'Mis favoritos',
    loadingWishlist: 'Cargando favoritos...',
    wishlistEmpty: 'Tu lista de favoritos está vacía',
    addCarsFromHome: 'Añade coches desde Inicio para verlos aquí.',
    couldNotLoadWishlist: 'No se pudieron cargar los favoritos.',

    // Messages / chat
    chats: 'Chats',
    loadingConversations: 'Cargando conversaciones...',
    noConversationsYet: 'Todavía no hay conversaciones.',
    contactSellerFromDetail: 'Contacta con un vendedor desde la ficha de un vehículo.',
    conversationStarted: 'Conversación iniciada',
    yesterday: 'Ayer',
    couldNotLoadConversations: 'No se pudieron cargar las conversaciones.',
    conversation: 'Conversación',
    loadingMessages: 'Cargando mensajes...',
    noMessagesYet: 'Todavía no hay mensajes.',
    sendFirstMessage: 'Envía el primer mensaje sobre este vehículo.',
    vehicleOffer: 'Oferta por el vehículo',
    buyer: 'Comprador',
    buyerOffers: '{buyer} ofrece',
    accept: 'Aceptar',
    reject: 'Rechazar',
    offerAccepted: 'Oferta aceptada',
    offerRejected: 'Oferta rechazada',
    sellerAcceptedOffer: 'El vendedor ha aceptado tu oferta.',
    sellerRejectedOffer: 'El vendedor ha rechazado tu oferta.',
    orderDelivered: 'Pedido entregado',
    orderDeliveredText: 'El pedido ha llegado a su destino.',
    completed: 'COMPLETADO',
    view: 'Ver',
    messagePlaceholder: 'Mensaje...',
    couldNotLoadChat: 'No se pudo cargar el chat.',
    couldNotSendMessage: 'No se pudo enviar el mensaje.',
    couldNotAnswerOffer: 'No se pudo responder a la oferta.',

    // Orders
    myOrders: 'Mis pedidos',
    active: 'Activos',
    noActiveOrders: 'No hay pedidos activos',
    acceptedOffersAppear: 'Las ofertas aceptadas aparecerán aquí después del checkout.',
    trackOrder: 'Seguir pedido',
    noCompletedOrders: 'No hay pedidos completados',
    deliveredOrdersAppear: 'Los pedidos entregados aparecerán aquí.',
    leaveReview: 'Dejar reseña',
    reviewSimulated: 'Reseña para {id} (simulada)',
  },
} as const;

export const usePreferencesStore = defineStore('preferences', {
  state: () => ({
    language: readLanguage() as AppLanguage,
    address: { country: '', city: '', address: '' } as UserAddress,
  }),

  getters: {
    languageLabel: (state) => state.language === 'es' ? translations.es.spanish : translations.en.english,
  },

  actions: {
    init(userId?: number | string | null) {
      this.language = readLanguage();
      this.address = readAddress(userId);
      document.documentElement.lang = this.language;
    },

    setLanguage(language: AppLanguage) {
      this.language = language;
      window.localStorage.setItem(LANGUAGE_KEY, language);
      document.documentElement.lang = language;
    },

    setAddress(userId: number | string | null | undefined, address: UserAddress) {
      this.address = address;
      writeAddress(userId, address);
    },

    t(key: keyof typeof translations.en, values?: Record<string, string | number>) {
      let text: string = translations[this.language][key] || translations.en[key] || key;
      if (values) {
        Object.entries(values).forEach(([name, value]) => {
          text = text.replace(`{${name}}`, String(value));
        });
      }
      return text;
    },
  },
});